[package]
name = "snake_game"
version = "0.1.0"
authors = ["vagrant <vagrant@ubuntu.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
volatile = "0.1.0"
spin = "0.5.2"
uart_16550 = "0.2.0"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]
